<a href="https://colab.research.google.com/github/anamikaYadav7376/python-/blob/main/Day_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Numpy Library = array/vaector

# python do not have arrays thats why we need it

import numpy as np  # np = elias

#a = numpy.array([1,3,9,0,2])  # if i do not take elias
#print(a)


In [ ]:
z = np.array([1,3,4,5,'0'])
print(z)

# it change integer in string

['1' '3' '4' '5' '0']


In [ ]:
v = np.array([2,3,5,'hello',False])

# true = cuz v[-1] is string and bool of a value is true always
print(bool(v[-1]))

a= False
print(bool(a))

True
False


In [ ]:
a = np.zeros(3) # 1D
b=np.zeros((2,3,4), dtype=int) # 3D

print(a)
print (b)

[0. 0. 0.]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
a = np.ones(3) # 1D
b=np.ones((2,3,4), dtype=int) # 3D

print(a)
print (b)

[1. 1. 1.]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
a = np.empty(2, dtype=int) # random value (garbage)

print(a)

[ 3077078788606746707 -3463510529963598224]


In [ ]:
a = np.full(2,8, dtype=int)

print(a)

[8 8]


In [ ]:
# np.arange(start, stop, step)

x = np.arange(0,6,2)
print(x)

[0 2 4]


In [ ]:
# np.linspace(start, stop, num=50, endpoint=True)
# Start at 0, end exactly at 10, give me 5 values total
arr = np.linspace(0, 10, 5)
print(arr)  # Output: [ 0.   2.5  5.   7.5 10. ]


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
a = np.array([1,2,3,77])
print(a.shape,a.size)

# shape , size , dtype

(4,) 4


In [ ]:
# random.randint()
# random.choice()  // choice from a perticular given array

g = np.random.randint(1,7,4)
print(g)

h = np.random.choice([23,34,56,78,90],2)
print (h)

[2 4 5 5]
[23 78]


# BroadCasting

vector and matrices operations and comparision with list operation

In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
# on corresponding elements are +-/* works
print(2*a)
print(a*b)
print(a+b)

# when we do these opration on deifferent dimention array it will gives error

c = [1,2,3,4,5]
d = [6,9,2,0]
print(c+d)  # it will concanitate when it is not array

[ 2  4  6  8 10 12]
[ 1  4  9 16 25 36]
[ 2  4  6  8 10 12]
[1, 2, 3, 4, 5, 6, 9, 2, 0]


In [ ]:
a = np.random.randint(2,15,6)
print(a)

# we can change dimention
b = a.reshape((2,3))  # 2D
print(b)

c = a.reshape((3,2))  # still 2D
print(c)

[ 2  8  8 14  8  4]
[[ 2  8  8]
 [14  8  4]]
[[ 2  8]
 [ 8 14]
 [ 8  4]]


In [ ]:
i = np.random.randint(2,15,9)

j = np.random.randint(2,15,9)


k = np.concatenate((i,j))
print (k)

result = np.array([i,j])
print(result)

# Shapes: a is (2, 2), b is (1, 2)
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])

# Goal: Append 'b' as a new column.
# Problem: We cannot concatenate (2, 2) and (1, 2) along axis=1.
# Solution: Transpose 'b' to shape (2, 1) first.
result = np.concatenate((a, b.T), axis=1)

print(result)

[ 9  2  8  3 11  8  9 10 14 10 12  2  8  7  9  6  5  5]
[[ 9  2  8  3 11  8  9 10 14]
 [10 12  2  8  7  9  6  5  5]]
[[1 2 5]
 [3 4 6]]


In [ ]:
a = np.random.randint(2,15,9)
b = np.random.randint(2,15,9)
print(a)
print(b)
c = np.where(b>2,b,a)
print (c)


[ 7  9  3  5  7 11  7 14  2]
[ 8 14 10  7 12  8 12  7  5]
[ 8 14 10  7 12  8 12  7  5]


In [ ]:
# sort(),sum(),mean(),std(),min(),max(),unique(),matmul()

a = np.random.randint(2,15,9)
b=np.random.randint(2,15,9)

print(np.sort(a))

print(np.sum(a))

print(np.mean(a))

print(np.std(a))

print(np.min(a))

print(np.max(a))

print(np.unique(a))

print(np.matmul(a,b))

[ 3  3  3  4  4  4  4 12 14]
51
5.666666666666667
3.9721250959376615
3
14
[ 3  4 12 14]
522


In [ ]:
Cricket = np.random.randint(0, 151, size=7)
print(Cricket)
total_score = np.sum(Cricket)
print(total_score)
max_score = np.max(Cricket)
print(max_score)
min_score = np.min(Cricket)
print(min_score)
average_score = np.mean(Cricket)
print(average_score)
standard_deviation = np.std(Cricket)
print(standard_deviation)



scores = []
days = ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun']
for day in range(7):
  score = input(f"Enter the score for {days[day]}: ")
  scores.append(score)

[131  19 140  84  71  40 102]
587
140
19
83.85714285714286
41.40196189771195


In [ ]:
a = np.array([3,3,3,3])

b=a
# copy concept
b[0]=1

print(a,b)

[1 3 3 3] [1 3 3 3]


In [5]:
import numpy as np
prices = []
items = ["Rice", "Sugar", "Milk", "Oil",
         "Tea", "Soap", "Biscuits"]
for item in items:
    price = float(input(f"Enter price of {item}: "))
    prices.append(price)
prices = np.array(prices)
print("Prices:", prices)
print("Max Price:", np.max(prices))
print("Min  Price:", np.min(prices))
print("Avg Price:", np.mean(prices))
print("Std dev:", np.std(prices))

Enter price of Rice: 35
Enter price of Sugar: 27
Enter price of Milk: 28
Enter price of Oil: 78
Enter price of Tea: 56
Enter price of Soap: 90
Enter price of Biscuits: 435
Prices: [ 35.  27.  28.  78.  56.  90. 435.]
Max Price: 435.0
Min  Price: 27.0
Avg Price: 107.0
Std dev: 135.82551832616517


In [14]:
import numpy as np

matrix = np.random.randint(1, 91, (5,5))

print(matrix)

# Find mean of values row and column wise

print(np.mean(matrix, axis=1))  # row - wise
print(np.mean(matrix, axis=0) ) # column-wise

# Replace all even numbers with -1

# matrix[matrix % 2 == 0] = -1
# print(matrix)

# OR

modified_Mat = np.where(matrix % 2 == 0, -1, matrix)
print(modified_Mat)

# To Sort the array row and column wise

print(np.sort(matrix, axis=1))
print(np.sort(matrix, axis=0))

# Find row and column wise sum saparately

Row_sum = np.sum(matrix, axis=1)
print("Row sum : ", Row_sum)

Col_sum = np.sum(matrix, axis=0)
print("Col sum : ", Col_sum)

# count the "-ve" and where

# print(np.sum(matrix < 0, axis=0))

cnt = np.sum(np.where(modified_Mat < 0, 1 , 0))
print("Number of negative : ",cnt)

[[73 37 54 87 25]
 [17 36 20 82 41]
 [69 38 88  3 26]
 [69  2 47 87 62]
 [40 11  1 82 43]]
[55.2 39.2 44.8 53.4 35.4]
[53.6 24.8 42.  68.2 39.4]
[[73 37 -1 87 25]
 [17 -1 -1 -1 41]
 [69 -1 -1  3 -1]
 [69 -1 47 87 -1]
 [-1 11  1 -1 43]]
[[25 37 54 73 87]
 [17 20 36 41 82]
 [ 3 26 38 69 88]
 [ 2 47 62 69 87]
 [ 1 11 40 43 82]]
[[17  2  1  3 25]
 [40 11 20 82 26]
 [69 36 47 82 41]
 [69 37 54 87 43]
 [73 38 88 87 62]]
Row sum :  [276 196 224 267 177]
Col sum :  [268 124 210 341 197]
Number of negative :  11


In [28]:
stock = np.random.randint(30,100,(5,5))
print(stock)

demand = np.random.randint(1,100,(5,5))
print(demand)

remaining_stock = stock - demand
print(remaining_stock)

# Replace
replace = np.where(remaining_stock < 0, 0, remaining_stock)
print(replace)

# Find total shortage

total_shortage = np.sum(np.where(remaining_stock < 0, remaining_stock*-1, 0))
print(total_shortage)

# Product with zero stock

zero_stock_products = np.sum(np.where(replace==0,1,0), axis=0)
print(zero_stock_products)

# Sort each row based on remaining stocks

row_sort = np.sort(remaining_stock, axis=1)
print(row_sort)

[[80 84 90 34 56]
 [80 49 98 57 65]
 [61 79 71 93 47]
 [79 55 51 30 66]
 [41 81 60 59 68]]
[[28 37  9 33 70]
 [72 42 52 79 48]
 [51 16 64 82 25]
 [91 46 47 57 70]
 [67 61 81 21 38]]
[[ 52  47  81   1 -14]
 [  8   7  46 -22  17]
 [ 10  63   7  11  22]
 [-12   9   4 -27  -4]
 [-26  20 -21  38  30]]
[[52 47 81  1  0]
 [ 8  7 46  0 17]
 [10 63  7 11 22]
 [ 0  9  4  0  0]
 [ 0 20  0 38 30]]
126
[2 0 1 2 2]
[[-14   1  47  52  81]
 [-22   7   8  17  46]
 [  7  10  11  22  63]
 [-27 -12  -4   4   9]
 [-26 -21  20  30  38]]
